[package]
name = "quible-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
jsonrpsee = { version = "0.24.3", features = ["http-client", "server", "client", "macros"] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
surrealdb = "1.5.4"
tokio = { version = "1.39.2", features = ["macros", "rt", "rt-multi-thread", "time"] }

[[bin]]
name = "client"
path = "src/client.rs"
