name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: the-rust-cache
      - run: cargo install cargo-deb --locked
      - run: cargo test --verbose
      - run: cargo build --features surrealdb/protocol-ws --release --target=x86_64-unknown-linux-gnu --verbose
      - run: cargo deb --no-build --target=x86_64-unknown-linux-gnu --output target/x86_64-unknown-linux-gnu/debian/quible-node_${GITHUB_SHA::7}_amd64.deb
      - run: echo ${GITHUB_SHA::7} > target/x86_64-unknown-linux-gnu/debian/latest
      - name: Archive debian artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: |
            target/x86_64-unknown-linux-gnu/debian/*.deb
            target/x86_64-unknown-linux-gnu/debian/latest
