name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo install cargo-deb
      - run: cargo test --verbose
      - run: cargo build --features surrealdb/protocol-ws --release --target=x86_64-unknown-linux-gnu --verbose
      - run: cargo deb --no-build --target=x86_64-unknown-linux-gnu
